// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"database/sql"
)

type SchemaMetum struct {
	Key       string
	Value     string
	UpdatedAt string
}

type SecurityAuditEvent struct {
	ID            string
	OccurredAt    string
	ActorUserID   sql.NullString
	SubjectUserID sql.NullString
	EventType     string
	Result        string
	IpHash        sql.NullString
	UserAgentHash sql.NullString
	MetadataJson  sql.NullString
}

type Session struct {
	ID               string
	SessionTokenHash string
	UserID           string
	CsrfTokenHash    string
	CreatedAt        string
	ExpiresAt        string
	IdleExpiresAt    string
	LastSeenAt       string
	RevokedAt        sql.NullString
	UserAgentHash    sql.NullString
	IpHash           sql.NullString
}

type Setting struct {
	Namespace string
	Key       string
	Value     string
	ValueType string
	UpdatedAt string
}

type User struct {
	ID                 string
	Username           string
	DisplayName        sql.NullString
	PasswordHash       string
	Role               string
	Status             string
	MustChangePassword int64
	CreatedAt          string
	UpdatedAt          string
	LastLoginAt        sql.NullString
}
