// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

type SchemaMetum struct {
	Key       string
	Value     string
	UpdatedAt string
}

type Setting struct {
	Namespace string
	Key       string
	Value     string
	ValueType string
	UpdatedAt string
}
