// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlcgen

import (
	"context"
)

type Querier interface {
	GetSetting(ctx context.Context, arg GetSettingParams) (Setting, error)
	ListSettingsByNamespace(ctx context.Context, namespace string) ([]Setting, error)
	UpsertSetting(ctx context.Context, arg UpsertSettingParams) error
}

var _ Querier = (*Queries)(nil)
