// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: security_audit.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const appendSecurityAuditEvent = `-- name: AppendSecurityAuditEvent :exec
INSERT INTO security_audit_events (
    id, actor_user_id, subject_user_id, event_type, result,
    ip_hash, user_agent_hash, metadata_json, occurred_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, datetime('now')
)
`

type AppendSecurityAuditEventParams struct {
	ID            string
	ActorUserID   sql.NullString
	SubjectUserID sql.NullString
	EventType     string
	Result        string
	IpHash        sql.NullString
	UserAgentHash sql.NullString
	MetadataJson  sql.NullString
}

func (q *Queries) AppendSecurityAuditEvent(ctx context.Context, arg AppendSecurityAuditEventParams) error {
	_, err := q.db.ExecContext(ctx, appendSecurityAuditEvent,
		arg.ID,
		arg.ActorUserID,
		arg.SubjectUserID,
		arg.EventType,
		arg.Result,
		arg.IpHash,
		arg.UserAgentHash,
		arg.MetadataJson,
	)
	return err
}

const listSecurityAuditEvents = `-- name: ListSecurityAuditEvents :many
SELECT
    id, occurred_at, actor_user_id, subject_user_id, event_type, result,
    ip_hash, user_agent_hash, metadata_json
FROM security_audit_events
WHERE (
    ?1 IS NULL
    OR occurred_at < ?1
    OR (
        occurred_at = ?1
        AND id < ?2
    )
)
ORDER BY occurred_at DESC, id DESC
LIMIT ?3
`

type ListSecurityAuditEventsParams struct {
	AfterOccurredAt interface{}
	AfterID         sql.NullString
	RowLimit        int64
}

func (q *Queries) ListSecurityAuditEvents(ctx context.Context, arg ListSecurityAuditEventsParams) ([]SecurityAuditEvent, error) {
	rows, err := q.db.QueryContext(ctx, listSecurityAuditEvents, arg.AfterOccurredAt, arg.AfterID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SecurityAuditEvent{}
	for rows.Next() {
		var i SecurityAuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorUserID,
			&i.SubjectUserID,
			&i.EventType,
			&i.Result,
			&i.IpHash,
			&i.UserAgentHash,
			&i.MetadataJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
