// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_auth.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const getSessionAuthByTokenHash = `-- name: GetSessionAuthByTokenHash :one
SELECT
    s.id AS session_id,
    s.user_id,
    s.expires_at,
    s.idle_expires_at,
    s.revoked_at,
    s.csrf_token_hash,
    u.status AS user_status,
    u.role AS user_role
FROM sessions s
INNER JOIN users u ON u.id = s.user_id
WHERE s.session_token_hash = ?
`

type GetSessionAuthByTokenHashRow struct {
	SessionID     string
	UserID        string
	ExpiresAt     string
	IdleExpiresAt string
	RevokedAt     sql.NullString
	CsrfTokenHash string
	UserStatus    string
	UserRole      string
}

func (q *Queries) GetSessionAuthByTokenHash(ctx context.Context, sessionTokenHash string) (GetSessionAuthByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionAuthByTokenHash, sessionTokenHash)
	var i GetSessionAuthByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.RevokedAt,
		&i.CsrfTokenHash,
		&i.UserStatus,
		&i.UserRole,
	)
	return i, err
}
