// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (
    id, session_token_hash, user_id, csrf_token_hash,
    expires_at, idle_expires_at, user_agent_hash, ip_hash,
    created_at, last_seen_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now')
)
`

type CreateSessionParams struct {
	ID               string
	SessionTokenHash string
	UserID           string
	CsrfTokenHash    string
	ExpiresAt        string
	IdleExpiresAt    string
	UserAgentHash    sql.NullString
	IpHash           sql.NullString
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.SessionTokenHash,
		arg.UserID,
		arg.CsrfTokenHash,
		arg.ExpiresAt,
		arg.IdleExpiresAt,
		arg.UserAgentHash,
		arg.IpHash,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at < datetime('now')
   OR idle_expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT
    id, user_id, session_token_hash, csrf_token_hash,
    created_at, expires_at, idle_expires_at, last_seen_at, revoked_at,
    user_agent_hash, ip_hash
FROM sessions
WHERE session_token_hash = ?
`

type GetSessionByTokenHashRow struct {
	ID               string
	UserID           string
	SessionTokenHash string
	CsrfTokenHash    string
	CreatedAt        string
	ExpiresAt        string
	IdleExpiresAt    string
	LastSeenAt       string
	RevokedAt        sql.NullString
	UserAgentHash    sql.NullString
	IpHash           sql.NullString
}

func (q *Queries) GetSessionByTokenHash(ctx context.Context, sessionTokenHash string) (GetSessionByTokenHashRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByTokenHash, sessionTokenHash)
	var i GetSessionByTokenHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SessionTokenHash,
		&i.CsrfTokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.IdleExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.UserAgentHash,
		&i.IpHash,
	)
	return i, err
}

const revokeAllSessionsForUser = `-- name: RevokeAllSessionsForUser :exec
UPDATE sessions
SET revoked_at = ?
WHERE user_id = ? AND revoked_at IS NULL
`

type RevokeAllSessionsForUserParams struct {
	RevokedAt sql.NullString
	UserID    string
}

func (q *Queries) RevokeAllSessionsForUser(ctx context.Context, arg RevokeAllSessionsForUserParams) error {
	_, err := q.db.ExecContext(ctx, revokeAllSessionsForUser, arg.RevokedAt, arg.UserID)
	return err
}

const revokeSessionByID = `-- name: RevokeSessionByID :exec
UPDATE sessions
SET revoked_at = ?
WHERE id = ?
`

type RevokeSessionByIDParams struct {
	RevokedAt sql.NullString
	ID        string
}

func (q *Queries) RevokeSessionByID(ctx context.Context, arg RevokeSessionByIDParams) error {
	_, err := q.db.ExecContext(ctx, revokeSessionByID, arg.RevokedAt, arg.ID)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = ?
WHERE id = ?
`

type TouchSessionParams struct {
	LastSeenAt string
	ID         string
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.ExecContext(ctx, touchSession, arg.LastSeenAt, arg.ID)
	return err
}
