// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: settings.sql

package sqlcgen

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT namespace, key, value, value_type, updated_at
FROM settings
WHERE namespace = ? AND key = ?
`

type GetSettingParams struct {
	Namespace string
	Key       string
}

func (q *Queries) GetSetting(ctx context.Context, arg GetSettingParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSetting, arg.Namespace, arg.Key)
	var i Setting
	err := row.Scan(
		&i.Namespace,
		&i.Key,
		&i.Value,
		&i.ValueType,
		&i.UpdatedAt,
	)
	return i, err
}

const listSettingsByNamespace = `-- name: ListSettingsByNamespace :many
SELECT namespace, key, value, value_type, updated_at
FROM settings
WHERE namespace = ?
ORDER BY key
`

func (q *Queries) ListSettingsByNamespace(ctx context.Context, namespace string) ([]Setting, error) {
	rows, err := q.db.QueryContext(ctx, listSettingsByNamespace, namespace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Setting{}
	for rows.Next() {
		var i Setting
		if err := rows.Scan(
			&i.Namespace,
			&i.Key,
			&i.Value,
			&i.ValueType,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (namespace, key, value, value_type, updated_at)
VALUES (?, ?, ?, ?, datetime('now'))
ON CONFLICT (namespace, key) DO UPDATE SET
    value = excluded.value,
    value_type = excluded.value_type,
    updated_at = datetime('now')
`

type UpsertSettingParams struct {
	Namespace string
	Key       string
	Value     string
	ValueType string
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting,
		arg.Namespace,
		arg.Key,
		arg.Value,
		arg.ValueType,
	)
	return err
}
