// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS count
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id, username, display_name, password_hash, role, status, must_change_password,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, datetime('now'), datetime('now')
)
`

type CreateUserParams struct {
	ID                 string
	Username           string
	DisplayName        sql.NullString
	PasswordHash       string
	Role               string
	Status             string
	MustChangePassword int64
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.DisplayName,
		arg.PasswordHash,
		arg.Role,
		arg.Status,
		arg.MustChangePassword,
	)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id, username, display_name, role, status, must_change_password,
    created_at, updated_at, last_login_at
FROM users
WHERE id = ?
`

type GetUserByIDRow struct {
	ID                 string
	Username           string
	DisplayName        sql.NullString
	Role               string
	Status             string
	MustChangePassword int64
	CreatedAt          string
	UpdatedAt          string
	LastLoginAt        sql.NullString
}

func (q *Queries) GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id, username, display_name, password_hash, role, status, must_change_password,
    created_at, updated_at, last_login_at
FROM users
WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.DisplayName,
		&i.PasswordHash,
		&i.Role,
		&i.Status,
		&i.MustChangePassword,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT
    id, username, display_name, role, status, must_change_password,
    created_at, updated_at, last_login_at
FROM users
WHERE (
    ?1 = ''
    OR username > ?1
)
ORDER BY username COLLATE NOCASE ASC
LIMIT ?2
`

type ListUsersParams struct {
	AfterUsername interface{}
	RowLimit      int64
}

type ListUsersRow struct {
	ID                 string
	Username           string
	DisplayName        sql.NullString
	Role               string
	Status             string
	MustChangePassword int64
	CreatedAt          string
	UpdatedAt          string
	LastLoginAt        sql.NullString
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.AfterUsername, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.Role,
			&i.Status,
			&i.MustChangePassword,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserStatus = `-- name: SetUserStatus :exec
UPDATE users
SET status = ?, updated_at = datetime('now')
WHERE id = ?
`

type SetUserStatusParams struct {
	Status string
	ID     string
}

func (q *Queries) SetUserStatus(ctx context.Context, arg SetUserStatusParams) error {
	_, err := q.db.ExecContext(ctx, setUserStatus, arg.Status, arg.ID)
	return err
}

const updateUserLastLoginAt = `-- name: UpdateUserLastLoginAt :exec
UPDATE users
SET last_login_at = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateUserLastLoginAtParams struct {
	LastLoginAt sql.NullString
	ID          string
}

func (q *Queries) UpdateUserLastLoginAt(ctx context.Context, arg UpdateUserLastLoginAtParams) error {
	_, err := q.db.ExecContext(ctx, updateUserLastLoginAt, arg.LastLoginAt, arg.ID)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE users
SET password_hash = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateUserPasswordHashParams struct {
	PasswordHash string
	ID           string
}

func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.ExecContext(ctx, updateUserPasswordHash, arg.PasswordHash, arg.ID)
	return err
}
