package installwrite

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func createStateDirectories(targetRoot string) error {
	for _, rel := range stateDirectories {
		path := filepath.Join(targetRoot, filepath.FromSlash(rel))
		if err := os.MkdirAll(path, 0o755); err != nil {
			return fmt.Errorf("%w: create directory %s: %v", ErrInstallFailed, rel, err)
		}
	}
	return nil
}

func copyPayload(entry CopyEntry, targetRoot string) error {
	info, err := os.Stat(entry.SourcePath)
	if err != nil || info.IsDir() {
		return fmt.Errorf("%w: missing source %s", ErrInstallFailed, entry.TargetRel)
	}
	if entry.ExpectedSize > 0 && uint64(info.Size()) != entry.ExpectedSize {
		return fmt.Errorf("%w: source size mismatch for %s", ErrInstallFailed, entry.TargetRel)
	}

	dest := filepath.Join(targetRoot, filepath.FromSlash(entry.TargetRel))
	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return fmt.Errorf("%w: mkdir for %s: %v", ErrInstallFailed, entry.TargetRel, err)
	}

	data, err := os.ReadFile(entry.SourcePath)
	if err != nil {
		return fmt.Errorf("%w: read source %s: %v", ErrInstallFailed, entry.TargetRel, err)
	}
	if err := os.WriteFile(dest, data, entry.Mode); err != nil {
		return fmt.Errorf("%w: write target %s: %v", ErrInstallFailed, entry.TargetRel, err)
	}
	return nil
}

func postVerify(targetRoot string, plan []CopyEntry) error {
	for _, entry := range plan {
		dest := filepath.Join(targetRoot, filepath.FromSlash(entry.TargetRel))
		info, err := os.Stat(dest)
		if err != nil || info.IsDir() {
			return fmt.Errorf("%w: missing copied payload %s", ErrPostVerifyFailed, entry.TargetRel)
		}
		if entry.ExpectedSize > 0 && uint64(info.Size()) != entry.ExpectedSize {
			return fmt.Errorf("%w: size mismatch for %s", ErrPostVerifyFailed, entry.TargetRel)
		}
		if entry.ExpectedSHA256 != "" {
			sum, err := fileSHA256(dest)
			if err != nil {
				return fmt.Errorf("%w: hash %s: %v", ErrPostVerifyFailed, entry.TargetRel, err)
			}
			if sum != entry.ExpectedSHA256 {
				return fmt.Errorf("%w: sha256 mismatch for %s", ErrPostVerifyFailed, entry.TargetRel)
			}
		}
	}

	if err := rejectForbiddenFiles(targetRoot); err != nil {
		return err
	}
	return verifyPayloadInventory(targetRoot, plan)
}

func rejectForbiddenFiles(targetRoot string) error {
	return filepath.WalkDir(targetRoot, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		base := strings.ToLower(d.Name())
		if strings.HasSuffix(base, ".db") || strings.HasSuffix(base, ".sqlite") || strings.HasSuffix(base, ".sqlite3") {
			return fmt.Errorf("%w: forbidden database file %s", ErrPostVerifyFailed, path)
		}
		return nil
	})
}

func verifyPayloadInventory(targetRoot string, plan []CopyEntry) error {
	allowed := make(map[string]struct{}, len(plan)+1)
	for _, entry := range plan {
		allowed[entry.TargetRel] = struct{}{}
	}
	allowed[InstallRecordName] = struct{}{}

	count := 0
	err := filepath.WalkDir(targetRoot, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		rel, err := filepath.Rel(targetRoot, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if _, ok := allowed[rel]; !ok {
			return fmt.Errorf("%w: unexpected file %s", ErrPostVerifyFailed, rel)
		}
		count++
		return nil
	})
	if err != nil {
		return err
	}
	if count != len(plan) {
		return fmt.Errorf("%w: expected %d payload files before record, found %d", ErrPostVerifyFailed, len(plan), count)
	}
	return nil
}

func writeInstallRecord(targetRoot, diskID, releaseVersion string, plan []CopyEntry, hostMutated bool) error {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by vyntrio-installer install — do not commit\n")
	fmt.Fprintf(&b, "schema_version: %s\n", SchemaVersion)
	fmt.Fprintf(&b, "generated_at: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "target_disk_id: %s\n", diskID)
	fmt.Fprintf(&b, "release_version: %s\n", releaseVersion)
	fmt.Fprintf(&b, "payloads_copied: %d\n", len(plan))
	fmt.Fprintf(&b, "service_enablement: deferred\n")
	fmt.Fprintf(&b, "bootstrap_handoff: deferred\n")
	fmt.Fprintf(&b, "host_block_device_mutated: %t\n", hostMutated)
	fmt.Fprintf(&b, "copied_payloads:\n")
	for _, entry := range plan {
		fmt.Fprintf(&b, "  - /%s\n", entry.TargetRel)
	}
	path := filepath.Join(targetRoot, InstallRecordName)
	return os.WriteFile(path, []byte(b.String()), 0o644)
}
