package installtarget

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// Applier performs guarded target mount preparation for payload application.
type Applier struct {
	Reader      DeviceReader
	Mounter     MountController
	Prober      FSProber
	Partitions  PartitionLister
}

// NewApplier creates an applier with platform defaults.
func NewApplier(stateDir string) Applier {
	return Applier{
		Reader:     NewInventoryAdapter(stateDir),
		Mounter:    defaultMountController(),
		Prober:     defaultFSProber(),
		Partitions: defaultPartitionLister(),
	}
}

// MountSession is an active mounted target used for payload writes.
type MountSession struct {
	DiskID     string
	MountPoint string
	Candidate  MountCandidate
	mounter    MountController
}

// Unmount releases the mount session.
func (s MountSession) Unmount() error {
	if s.mounter == nil || strings.TrimSpace(s.MountPoint) == "" {
		return nil
	}
	return s.mounter.Unmount(s.MountPoint)
}

// Prepare validates the target and mounts a single supported filesystem.
func (a Applier) Prepare(req ApplyRequest) (MountSession, ApplyOutcome, error) {
	outcome := ApplyOutcome{DiskID: strings.TrimSpace(req.DiskID)}
	if !req.Force {
		outcome.FailureStage = "force"
		outcome.FailureReason = ErrForceRequired.Error()
		return MountSession{}, outcome, ErrForceRequired
	}
	if outcome.DiskID == "" {
		outcome.FailureStage = "target_disk_id"
		outcome.FailureReason = "target disk id required"
		return MountSession{}, outcome, ErrApplyFailed
	}

	stateDir := strings.TrimSpace(req.StateDir)
	device, err := lookupDevice(a.Reader, stateDir, outcome.DiskID)
	if err != nil {
		outcome.FailureStage = "target_resolve"
		outcome.FailureReason = err.Error()
		return MountSession{}, outcome, err
	}
	if err := validateDevice(device, outcome.DiskID); err != nil {
		outcome.FailureStage = "target_validate"
		outcome.FailureReason = err.Error()
		return MountSession{}, outcome, err
	}

	candidate, err := resolveMountCandidate(device.KernelName, a.Partitions, a.Prober, a.Reader, stateDir)
	if err != nil {
		outcome.FailureStage = "target_layout"
		outcome.FailureReason = err.Error()
		return MountSession{}, outcome, err
	}
	outcome.FSType = candidate.FSType

	mountPoint := mountPointFor(outcome.DiskID, req.MountRoot)
	if err := os.MkdirAll(filepath.Dir(mountPoint), 0o755); err != nil {
		outcome.FailureStage = "mount_prepare"
		outcome.FailureReason = err.Error()
		return MountSession{}, outcome, fmt.Errorf("%w: %v", ErrMountFailed, err)
	}
	if err := os.MkdirAll(mountPoint, 0o755); err != nil {
		outcome.FailureStage = "mount_prepare"
		outcome.FailureReason = err.Error()
		return MountSession{}, outcome, fmt.Errorf("%w: %v", ErrMountFailed, err)
	}

	if err := a.Mounter.Mount(candidate.DevicePath, mountPoint, candidate.FSType); err != nil {
		outcome.FailureStage = "mount"
		outcome.FailureReason = err.Error()
		_ = os.RemoveAll(mountPoint)
		return MountSession{}, outcome, fmt.Errorf("%w: %v", ErrMountFailed, err)
	}

	outcome.MountPoint = mountPoint
	outcome.Mounted = true
	outcome.Candidate = candidate
	session := MountSession{
		DiskID:     outcome.DiskID,
		MountPoint: mountPoint,
		Candidate:  candidate,
		mounter:    a.Mounter,
	}
	return session, outcome, nil
}

// WriteMutationRecord persists operator-visible mutation facts under stateDir.
func WriteMutationRecord(stateDir string, outcome ApplyOutcome, status string, payloadsCopied int, payloadPaths []string) (string, error) {
	dir := filepath.Join(strings.TrimSpace(stateDir), RecordDirName, outcome.DiskID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, MutationRecordName)
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by vyntrio-installer install --apply-target — do not commit\n")
	fmt.Fprintf(&b, "schema_version: %s\n", SchemaVersion)
	fmt.Fprintf(&b, "generated_at: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "status: %s\n", status)
	fmt.Fprintf(&b, "target_disk_id: %s\n", outcome.DiskID)
	fmt.Fprintf(&b, "mount_point: %s\n", outcome.MountPoint)
	fmt.Fprintf(&b, "device_path: %s\n", outcome.Candidate.DevicePath)
	fmt.Fprintf(&b, "fs_type: %s\n", outcome.FSType)
	fmt.Fprintf(&b, "rolled_back: %t\n", outcome.RolledBack)
	fmt.Fprintf(&b, "payloads_copied: %d\n", payloadsCopied)
	fmt.Fprintf(&b, "mutation_scope: mounted_partition_payload_copy_only\n")
	fmt.Fprintf(&b, "host_block_device_mutated: %t\n", status == StatusApplied)
	if outcome.FailureStage != "" {
		fmt.Fprintf(&b, "failure_stage: %s\n", outcome.FailureStage)
	}
	if outcome.FailureReason != "" {
		fmt.Fprintf(&b, "failure_reason: %s\n", outcome.FailureReason)
	}
	if len(payloadPaths) > 0 {
		fmt.Fprintf(&b, "copied_payloads:\n")
		for _, rel := range payloadPaths {
			fmt.Fprintf(&b, "  - /%s\n", rel)
		}
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
