package installapply

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// WriteApplyRecord persists operator-visible apply facts under stateDir.
func WriteApplyRecord(stateDir string, outcome Outcome, status string) (string, error) {
	dir := filepath.Join(strings.TrimSpace(stateDir), RecordDirName, outcome.TargetDiskID)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return "", err
	}
	path := filepath.Join(dir, ApplyRecordName)
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated by vyntrio-installer apply — do not commit\n")
	fmt.Fprintf(&b, "schema_version: %s\n", SchemaVersion)
	fmt.Fprintf(&b, "generated_at: %s\n", time.Now().UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "status: %s\n", status)
	fmt.Fprintf(&b, "target_disk_id: %s\n", outcome.TargetDiskID)
	fmt.Fprintf(&b, "partition_device_path: %s\n", outcome.PartitionDevicePath)
	fmt.Fprintf(&b, "mount_point: %s\n", outcome.MountPoint)
	fmt.Fprintf(&b, "fs_type: %s\n", outcome.TargetFSType)
	fmt.Fprintf(&b, "payloads_copied: %d\n", outcome.PayloadsCopied)
	fmt.Fprintf(&b, "apply_scope: %s\n", ScopeStatement)
	fmt.Fprintf(&b, "host_block_device_mutated: %t\n", status == StatusApplied)
	if outcome.FailureStage != "" {
		fmt.Fprintf(&b, "failure_stage: %s\n", outcome.FailureStage)
	}
	if outcome.FailureReason != "" {
		fmt.Fprintf(&b, "failure_reason: %s\n", outcome.FailureReason)
	}
	if len(outcome.PayloadPaths) > 0 {
		fmt.Fprintf(&b, "copied_payloads:\n")
		for _, rel := range outcome.PayloadPaths {
			fmt.Fprintf(&b, "  - /%s\n", rel)
		}
	}
	if err := os.WriteFile(path, []byte(b.String()), 0o644); err != nil {
		return "", err
	}
	return path, nil
}
