#!/usr/bin/env bash
# Assemble local install-media envelope per distro/install-media/envelope-contract.md.
# Consumes Slice 9.6 staging output; mirrors manifest payload paths (Slice 9.8).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGING_PAYLOAD="${ROOT}/distro/install-media/staging/payload"
ENVELOPE_ROOT="${ROOT}/distro/install-media/envelope"

# Manifest-listed payload paths under payload/ (mirrors stage-install-media.sh).
readonly -a PAYLOAD_FILES=(
	"usr/bin/vyntrio-api"
	"usr/bin/vyntrio-backup"
	"etc/systemd/system/vyntrio-api.service"
	"usr/lib/sysusers.d/vyntrio.conf"
	"etc/tmpfiles.d/vyntrio.conf"
	"etc/vyntrio/config.toml"
)

if [[ ! -d "${STAGING_PAYLOAD}" ]]; then
	echo "assemble-install-media-envelope: staging payload missing: distro/install-media/staging/payload" >&2
	echo "hint: run 'make install-media-stage' first" >&2
	exit 1
fi

for rel in "${PAYLOAD_FILES[@]}"; do
	if [[ ! -f "${STAGING_PAYLOAD}/${rel}" ]]; then
		echo "assemble-install-media-envelope: missing staged payload file: ${rel}" >&2
		echo "hint: run 'make install-media-stage' first" >&2
		exit 1
	fi
done

mapfile -t staged_files < <(find "${STAGING_PAYLOAD}" -type f | LC_ALL=C sort)
expected_count="${#PAYLOAD_FILES[@]}"
if [[ "${#staged_files[@]}" -ne "${expected_count}" ]]; then
	echo "assemble-install-media-envelope: unexpected file count in staging payload" >&2
	echo "expected: ${expected_count} manifest-listed files" >&2
	echo "found: ${#staged_files[@]}" >&2
	exit 1
fi

for rel in "${PAYLOAD_FILES[@]}"; do
	found=false
	for path in "${staged_files[@]}"; do
		if [[ "${path}" == "${STAGING_PAYLOAD}/${rel}" ]]; then
			found=true
			break
		fi
	done
	if [[ "${found}" != true ]]; then
		echo "assemble-install-media-envelope: staging payload contains unexpected paths" >&2
		echo "missing expected relative path: ${rel}" >&2
		exit 1
	fi
done

for path in "${staged_files[@]}"; do
	rel="${path#${STAGING_PAYLOAD}/}"
	expected=false
	for allowed in "${PAYLOAD_FILES[@]}"; do
		if [[ "${rel}" == "${allowed}" ]]; then
			expected=true
			break
		fi
	done
	if [[ "${expected}" != true ]]; then
		echo "assemble-install-media-envelope: non-manifest file in staging payload: ${rel}" >&2
		exit 1
	fi
done

rm -rf "${ENVELOPE_ROOT}"
mkdir -p "${ENVELOPE_ROOT}/boot" "${ENVELOPE_ROOT}/live_root" "${ENVELOPE_ROOT}/payload"

cp -a "${STAGING_PAYLOAD}/." "${ENVELOPE_ROOT}/payload/"

cat >"${ENVELOPE_ROOT}/boot/LAYER.txt" <<'EOF'
boot layer — deferred
No bootloader, kernel, or initrd in Slice 9.8 local assembly.
EOF

cat >"${ENVELOPE_ROOT}/live_root/LAYER.txt" <<'EOF'
live_root layer — deferred
No live root filesystem in Slice 9.8 local assembly.
EOF

{
	echo "# Generated by scripts/assemble-install-media-envelope.sh — do not commit"
	echo "schema_version: vyntrio-install-media-envelope-v1"
	echo "media_role: install"
	echo "envelope_root: distro/install-media/envelope/"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "layers:"
	echo "  boot: deferred"
	echo "  live_root: deferred"
	echo "  payload: assembled"
	echo "payload_files:"
	for rel in "${PAYLOAD_FILES[@]}"; do
		echo "  - payload/${rel}"
	done
} >"${ENVELOPE_ROOT}/ENVELOPE.txt"

echo "install-media envelope assembled under ${ENVELOPE_ROOT}"
