#!/usr/bin/env bash
# Preflight-gated installer mutation stub (dry-run only) — Slice 10.5.
# Authority: docs/ADR/0007-appliance-installer-contract.md
# Requires successful preflight and layout plan; does not mutate target disk.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DRY_RUN_ROOT="${ROOT}/distro/installer/dry-run"
LAYOUT_MANIFEST="${ROOT}/distro/installer/target-layout-manifest.yaml"

readonly -a PLANNED_DIRECTORIES=(
	"/etc/vyntrio"
	"/var/lib/vyntrio"
	"/var/lib/vyntrio/backups"
)

readonly -a PLANNED_PAYLOAD_TARGETS=(
	"/usr/bin/vyntrio-api"
	"/usr/bin/vyntrio-backup"
	"/etc/systemd/system/vyntrio-api.service"
	"/usr/lib/sysusers.d/vyntrio.conf"
	"/etc/tmpfiles.d/vyntrio.conf"
	"/etc/vyntrio/config.toml"
)

fail() {
	echo "installer-mutation-stub: FAIL: $*" >&2
	exit 1
}

ok() {
	echo "installer-mutation-stub: ok: $*"
}

echo "installer-mutation-stub: running preflight gate..."
if ! "${ROOT}/scripts/installer-preflight.sh" >/dev/null; then
	fail "preflight gate failed (install execution blocked)"
fi
ok "preflight gate passed"

echo "installer-mutation-stub: reading target-layout plan..."
if ! "${ROOT}/scripts/validate-installer-layout-plan.sh" >/dev/null; then
	fail "target-layout plan invalid"
fi
if [[ ! -f "${LAYOUT_MANIFEST}" ]]; then
	fail "target-layout manifest missing: distro/installer/target-layout-manifest.yaml"
fi
ok "target-layout plan consumed"

rm -rf "${DRY_RUN_ROOT}"
mkdir -p "${DRY_RUN_ROOT}"

{
	echo "# Generated by scripts/installer-mutation-stub.sh — do not commit"
	echo "schema_version: vyntrio-installer-mutation-stub-v1"
	echo "mode: dry_run"
	echo "target_disk_mutation: false"
	echo "contract: docs/ADR/0007-appliance-installer-contract.md"
	echo "layout_manifest: distro/installer/target-layout-manifest.yaml"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "preflight_gate: passed"
	echo "partition_layout: deferred"
	echo "planned_directories:"
	for dir in "${PLANNED_DIRECTORIES[@]}"; do
		echo "  - path: ${dir}"
		echo "    action: create_empty"
		echo "    executed: false"
	done
	echo "planned_payload_installs:"
	for target in "${PLANNED_PAYLOAD_TARGETS[@]}"; do
		echo "  - target: ${target}"
		echo "    action: copy_from_install_media_payload"
		echo "    executed: false"
	done
	echo "deferred_actions:"
	echo "  - partition_table_creation"
	echo "  - filesystem_formatting"
	echo "  - payload_copy_to_target"
	echo "  - service_enablement"
	echo "  - bootstrap_handoff"
} >"${DRY_RUN_ROOT}/MUTATION_STUB.txt"

ok "dry-run record written to distro/installer/dry-run/MUTATION_STUB.txt"
echo "installer-mutation-stub: complete — no target-disk mutation performed"
