#!/usr/bin/env bash
# Installer controlled service enablement (Slice 10.9).
# Authority: docs/ADR/0007-appliance-installer-contract.md
# Enables vyntrio-api.service in target-sandbox only; does not start services.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SANDBOX_ROOT="${ROOT}/distro/installer/target-sandbox"
TARGET_ROOT="${VYNTRIO_INSTALL_TARGET_ROOT:-${SANDBOX_ROOT}}"

readonly SERVICE_UNIT_REL="etc/systemd/system/vyntrio-api.service"
readonly SERVICE_PREP_MARKER_REL="etc/systemd/system/vyntrio-api.service.enable-prep"
readonly ENABLE_WANTS_DIR_REL="etc/systemd/system/multi-user.target.wants"
readonly ENABLE_SYMLINK_REL="${ENABLE_WANTS_DIR_REL}/vyntrio-api.service"
readonly PAYLOAD_COPY_RECORD="PAYLOAD_COPY.txt"
readonly SERVICE_PREP_RECORD="SERVICE_PREP.txt"

fail() {
	echo "installer-enable-service: FAIL: $*" >&2
	exit 1
}

ok() {
	echo "installer-enable-service: ok: $*"
}

resolve_path() {
	local path="$1"
	(
		cd "$(dirname "${path}")"
		echo "$(pwd -P)/$(basename "${path}")"
	)
}

resolved_target="$(resolve_path "${TARGET_ROOT}")"
resolved_sandbox="$(resolve_path "${SANDBOX_ROOT}")"

if [[ "${resolved_target}" != "${resolved_sandbox}" && "${resolved_target}" != "${resolved_sandbox}/"* ]]; then
	fail "unsafe target root: service enable restricted to distro/installer/target-sandbox/"
fi

echo "installer-enable-service: running preflight gate..."
if ! "${ROOT}/scripts/installer-preflight.sh" >/dev/null; then
	fail "preflight gate failed (service enable blocked)"
fi
ok "preflight gate passed"

echo "installer-enable-service: validating target-layout plan..."
if ! "${ROOT}/scripts/validate-installer-layout-plan.sh" >/dev/null; then
	fail "target-layout plan invalid"
fi
ok "target-layout plan consumed"

payload_copy_record="${resolved_target}/${PAYLOAD_COPY_RECORD}"
if [[ ! -f "${payload_copy_record}" ]]; then
	fail "payload copy record missing; run 'make installer-copy-payloads' first"
fi
if ! grep -q '^preflight_gate: passed$' "${payload_copy_record}"; then
	fail "payload copy gate not satisfied"
fi
ok "payload copy gate passed"

service_prep_record="${resolved_target}/${SERVICE_PREP_RECORD}"
if [[ ! -f "${service_prep_record}" ]]; then
	fail "service prep record missing; run 'make installer-prepare-service' first"
fi
if ! grep -q '^enablement_status: prepared_not_enabled$' "${service_prep_record}"; then
	fail "service prep gate not satisfied"
fi
prep_marker="${resolved_target}/${SERVICE_PREP_MARKER_REL}"
if [[ ! -f "${prep_marker}" ]]; then
	fail "service prep marker missing: ${SERVICE_PREP_MARKER_REL}"
fi
ok "service prep gate passed"

service_unit="${resolved_target}/${SERVICE_UNIT_REL}"
if [[ ! -s "${service_unit}" ]]; then
	fail "service unit missing or empty: ${SERVICE_UNIT_REL}"
fi
ok "service unit present: vyntrio-api.service"

wants_dir="${resolved_target}/${ENABLE_WANTS_DIR_REL}"
enable_symlink="${resolved_target}/${ENABLE_SYMLINK_REL}"
mkdir -p "${wants_dir}"
ln -sfn "../vyntrio-api.service" "${enable_symlink}"

if [[ ! -L "${enable_symlink}" ]]; then
	fail "enable symlink not created: ${ENABLE_SYMLINK_REL}"
fi
ok "systemd wants symlink created: ${ENABLE_SYMLINK_REL}"

cat >"${prep_marker}" <<'EOF'
# Installer service enablement marker (Slice 10.9)
# Not a running service — systemctl is not invoked.
status: enable_complete
unit: vyntrio-api.service
enabled: true
started: false
EOF
ok "enablement marker updated"

{
	echo "# Generated by scripts/installer-enable-service.sh — do not commit"
	echo "schema_version: vyntrio-installer-service-enable-v1"
	echo "slice: \"10.9\""
	echo "target_root: distro/installer/target-sandbox/"
	echo "host_paths_mutated: false"
	echo "host_services_started: false"
	echo "systemctl_invoked: false"
	echo "contract: docs/ADR/0007-appliance-installer-contract.md"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "preflight_gate: passed"
	echo "layout_plan_gate: passed"
	echo "payload_copy_gate: passed"
	echo "service_prep_gate: passed"
	echo "service_unit: /etc/systemd/system/vyntrio-api.service"
	echo "enablement_status: enabled_not_started"
	echo "service_started: false"
	echo "bootstrap_handoff: deferred"
	echo "enable_artifacts:"
	echo "  - etc/systemd/system/multi-user.target.wants/vyntrio-api.service"
} >"${resolved_target}/SERVICE_ENABLE.txt"

ok "service enable record written to target-sandbox/SERVICE_ENABLE.txt"
echo "installer-enable-service: complete — service enabled (no service start)"
