#!/usr/bin/env bash
# First installer target mutation: empty state directories only (Slice 10.6).
# Authority: docs/ADR/0007-appliance-installer-contract.md (section E)
# Requires preflight + layout plan. Mutates only repo-local target-sandbox/.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SANDBOX_ROOT="${ROOT}/distro/installer/target-sandbox"
TARGET_ROOT="${VYNTRIO_INSTALL_TARGET_ROOT:-${SANDBOX_ROOT}}"
LAYOUT_MANIFEST="${ROOT}/distro/installer/target-layout-manifest.yaml"

# Mirrors target-layout-manifest.yaml directories (absolute paths on real target).
readonly -a STATE_DIRECTORIES=(
	"etc/vyntrio"
	"var/lib/vyntrio"
	"var/lib/vyntrio/backups"
)

fail() {
	echo "installer-mutate-directories: FAIL: $*" >&2
	exit 1
}

ok() {
	echo "installer-mutate-directories: ok: $*"
}

resolve_path() {
	local path="$1"
	(
		cd "$(dirname "${path}")"
		echo "$(pwd -P)/$(basename "${path}")"
	)
}

resolved_target="$(resolve_path "${TARGET_ROOT}")"
resolved_sandbox="$(resolve_path "${SANDBOX_ROOT}")"

if [[ "${resolved_target}" != "${resolved_sandbox}" && "${resolved_target}" != "${resolved_sandbox}/"* ]]; then
	fail "unsafe target root: mutations restricted to distro/installer/target-sandbox/"
fi

echo "installer-mutate-directories: running preflight gate..."
if ! "${ROOT}/scripts/installer-preflight.sh" >/dev/null; then
	fail "preflight gate failed (mutation blocked)"
fi
ok "preflight gate passed"

echo "installer-mutate-directories: validating target-layout plan..."
if ! "${ROOT}/scripts/validate-installer-layout-plan.sh" >/dev/null; then
	fail "target-layout plan invalid"
fi
if [[ ! -f "${LAYOUT_MANIFEST}" ]]; then
	fail "target-layout manifest missing"
fi
ok "target-layout plan consumed"

rm -rf "${resolved_target}"
mkdir -p "${resolved_target}"

for rel in "${STATE_DIRECTORIES[@]}"; do
	mkdir -p "${resolved_target}/${rel}"
	if [[ -n "$(find "${resolved_target}/${rel}" -mindepth 1 -print -quit)" ]]; then
		fail "directory not empty after create: ${rel}"
	fi
done
ok "created ${#STATE_DIRECTORIES[@]} empty state directories"

# Fail-closed: no forbidden artifacts in sandbox.
if find "${resolved_target}" -type f \( -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' \) -print -quit | grep -q .; then
	fail "forbidden database file in target sandbox"
fi

{
	echo "# Generated by scripts/installer-mutate-directories.sh — do not commit"
	echo "schema_version: vyntrio-installer-mutation-v1"
	echo "slice: \"10.6\""
	echo "mode: directory_create_only"
	echo "target_root: distro/installer/target-sandbox/"
	echo "host_paths_mutated: false"
	echo "contract: docs/ADR/0007-appliance-installer-contract.md"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "preflight_gate: passed"
	echo "partition_layout: deferred"
	echo "payload_copy: deferred"
	echo "created_directories:"
	for rel in "${STATE_DIRECTORIES[@]}"; do
		echo "  - /${rel}"
	done
} >"${resolved_target}/MUTATION_RECORD.txt"

ok "mutation record written to target-sandbox/MUTATION_RECORD.txt"
echo "installer-mutate-directories: complete — empty state directories only (no payload copy)"
