#!/usr/bin/env bash
# Installer service enablement preparation (Slice 10.8).
# Authority: docs/ADR/0007-appliance-installer-contract.md
# Prepares service enablement artifacts in target-sandbox only; does not start services.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SANDBOX_ROOT="${ROOT}/distro/installer/target-sandbox"
TARGET_ROOT="${VYNTRIO_INSTALL_TARGET_ROOT:-${SANDBOX_ROOT}}"

readonly SERVICE_UNIT_REL="etc/systemd/system/vyntrio-api.service"
readonly SERVICE_PREP_MARKER_REL="etc/systemd/system/vyntrio-api.service.enable-prep"
readonly PAYLOAD_COPY_RECORD="PAYLOAD_COPY.txt"

readonly -a REQUIRED_PAYLOADS=(
	"usr/bin/vyntrio-api"
	"usr/bin/vyntrio-backup"
	"${SERVICE_UNIT_REL}"
	"usr/lib/sysusers.d/vyntrio.conf"
	"etc/tmpfiles.d/vyntrio.conf"
	"etc/vyntrio/config.toml"
)

fail() {
	echo "installer-prepare-service: FAIL: $*" >&2
	exit 1
}

ok() {
	echo "installer-prepare-service: ok: $*"
}

resolve_path() {
	local path="$1"
	(
		cd "$(dirname "${path}")"
		echo "$(pwd -P)/$(basename "${path}")"
	)
}

resolved_target="$(resolve_path "${TARGET_ROOT}")"
resolved_sandbox="$(resolve_path "${SANDBOX_ROOT}")"

if [[ "${resolved_target}" != "${resolved_sandbox}" && "${resolved_target}" != "${resolved_sandbox}/"* ]]; then
	fail "unsafe target root: service prep restricted to distro/installer/target-sandbox/"
fi

echo "installer-prepare-service: running preflight gate..."
if ! "${ROOT}/scripts/installer-preflight.sh" >/dev/null; then
	fail "preflight gate failed (service prep blocked)"
fi
ok "preflight gate passed"

echo "installer-prepare-service: validating target-layout plan..."
if ! "${ROOT}/scripts/validate-installer-layout-plan.sh" >/dev/null; then
	fail "target-layout plan invalid"
fi
ok "target-layout plan consumed"

payload_copy_record="${resolved_target}/${PAYLOAD_COPY_RECORD}"
if [[ ! -f "${payload_copy_record}" ]]; then
	fail "payload copy record missing; run 'make installer-copy-payloads' first"
fi
if ! grep -q '^preflight_gate: passed$' "${payload_copy_record}"; then
	fail "payload copy gate not satisfied"
fi
ok "payload copy gate passed"

for rel in "${REQUIRED_PAYLOADS[@]}"; do
	if [[ ! -f "${resolved_target}/${rel}" ]]; then
		fail "missing copied payload in target sandbox: ${rel}"
	fi
done
ok "target sandbox payloads verified (${#REQUIRED_PAYLOADS[@]} files)"

service_unit="${resolved_target}/${SERVICE_UNIT_REL}"
if [[ ! -s "${service_unit}" ]]; then
	fail "service unit missing or empty: ${SERVICE_UNIT_REL}"
fi
ok "service unit present: vyntrio-api.service"

prep_marker="${resolved_target}/${SERVICE_PREP_MARKER_REL}"
cat >"${prep_marker}" <<'EOF'
# Installer service enablement preparation marker (Slice 10.8)
# Not an active systemd enablement — systemctl is not invoked.
status: enable_pending
unit: vyntrio-api.service
enabled: false
started: false
EOF
ok "enablement prep marker written"

{
	echo "# Generated by scripts/installer-prepare-service.sh — do not commit"
	echo "schema_version: vyntrio-installer-service-prep-v1"
	echo "slice: \"10.8\""
	echo "target_root: distro/installer/target-sandbox/"
	echo "host_paths_mutated: false"
	echo "host_services_started: false"
	echo "contract: docs/ADR/0007-appliance-installer-contract.md"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "preflight_gate: passed"
	echo "layout_plan_gate: passed"
	echo "payload_copy_gate: passed"
	echo "service_unit: /etc/systemd/system/vyntrio-api.service"
	echo "enablement_status: prepared_not_enabled"
	echo "service_started: false"
	echo "bootstrap_handoff: deferred"
	echo "prep_artifacts:"
	echo "  - etc/systemd/system/vyntrio-api.service.enable-prep"
} >"${resolved_target}/SERVICE_PREP.txt"

ok "service prep record written to target-sandbox/SERVICE_PREP.txt"
echo "installer-prepare-service: complete — enablement prepared (no service start)"
