#!/usr/bin/env bash
# Installer target payload copy (Slice 10.7).
# Authority: docs/ADR/0007-appliance-installer-contract.md (section E)
# Copies manifest-listed payloads from install-media envelope to target-sandbox only.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SANDBOX_ROOT="${ROOT}/distro/installer/target-sandbox"
TARGET_ROOT="${VYNTRIO_INSTALL_TARGET_ROOT:-${SANDBOX_ROOT}}"
ENVELOPE_ROOT="${VYNTRIO_INSTALL_ENVELOPE_ROOT:-${ROOT}/distro/install-media/envelope}"
PAYLOAD_SOURCE="${VYNTRIO_INSTALL_PAYLOAD_ROOT:-${ENVELOPE_ROOT}/payload}"

# source_payload|target_relative (mirrors manifest install paths without leading /)
readonly -a PAYLOAD_COPY=(
	"usr/bin/vyntrio-api|usr/bin/vyntrio-api"
	"usr/bin/vyntrio-backup|usr/bin/vyntrio-backup"
	"etc/systemd/system/vyntrio-api.service|etc/systemd/system/vyntrio-api.service"
	"usr/lib/sysusers.d/vyntrio.conf|usr/lib/sysusers.d/vyntrio.conf"
	"etc/tmpfiles.d/vyntrio.conf|etc/tmpfiles.d/vyntrio.conf"
	"etc/vyntrio/config.toml|etc/vyntrio/config.toml"
)

fail() {
	echo "installer-copy-payloads: FAIL: $*" >&2
	exit 1
}

ok() {
	echo "installer-copy-payloads: ok: $*"
}

resolve_path() {
	local path="$1"
	(
		cd "$(dirname "${path}")"
		echo "$(pwd -P)/$(basename "${path}")"
	)
}

resolved_target="$(resolve_path "${TARGET_ROOT}")"
resolved_sandbox="$(resolve_path "${SANDBOX_ROOT}")"

if [[ "${resolved_target}" != "${resolved_sandbox}" && "${resolved_target}" != "${resolved_sandbox}/"* ]]; then
	fail "unsafe target root: copies restricted to distro/installer/target-sandbox/"
fi

echo "installer-copy-payloads: running preflight gate..."
if ! "${ROOT}/scripts/installer-preflight.sh" >/dev/null; then
	fail "preflight gate failed (payload copy blocked)"
fi
ok "preflight gate passed"

echo "installer-copy-payloads: validating target-layout plan..."
if ! "${ROOT}/scripts/validate-installer-layout-plan.sh" >/dev/null; then
	fail "target-layout plan invalid"
fi
ok "target-layout plan consumed"

if [[ ! -d "${PAYLOAD_SOURCE}" ]]; then
	fail "install payload source missing: ${PAYLOAD_SOURCE} (run 'make install-media-envelope' first)"
fi

for entry in "${PAYLOAD_COPY[@]}"; do
	src_rel="${entry%%|*}"
	if [[ ! -f "${PAYLOAD_SOURCE}/${src_rel}" ]]; then
		fail "missing source payload file: ${src_rel}"
	fi
done
ok "install payload source verified (${#PAYLOAD_COPY[@]} manifest files)"

# Ensure empty state directories exist (Slice 10.6 layout under sandbox).
for dir in etc/vyntrio var/lib/vyntrio var/lib/vyntrio/backups; do
	mkdir -p "${resolved_target}/${dir}"
done

for entry in "${PAYLOAD_COPY[@]}"; do
	src_rel="${entry%%|*}"
	dest_rel="${entry##*|}"
	src="${PAYLOAD_SOURCE}/${src_rel}"
	dest="${resolved_target}/${dest_rel}"
	mkdir -p "$(dirname "${dest}")"
	cp -a "${src}" "${dest}"
done
ok "copied ${#PAYLOAD_COPY[@]} manifest payloads to target-sandbox"

mapfile -t copied_files < <(find "${resolved_target}" -type f ! -name 'MUTATION_RECORD.txt' ! -name 'PAYLOAD_COPY.txt' | LC_ALL=C sort)
if [[ "${#copied_files[@]}" -ne "${#PAYLOAD_COPY[@]}" ]]; then
	fail "unexpected file count in target sandbox after copy (expected ${#PAYLOAD_COPY[@]}, found ${#copied_files[@]})"
fi

for entry in "${PAYLOAD_COPY[@]}"; do
	dest_rel="${entry##*|}"
	expected="${resolved_target}/${dest_rel}"
	found=false
	for path in "${copied_files[@]}"; do
		if [[ "${path}" == "${expected}" ]]; then
			found=true
			break
		fi
	done
	if [[ "${found}" != true ]]; then
		fail "missing copied payload in target sandbox: ${dest_rel}"
	fi
done

if find "${resolved_target}" -type f \( -name '*.db' -o -name '*.sqlite' -o -name '*.sqlite3' \) -print -quit | grep -q .; then
	fail "forbidden database file in target sandbox"
fi

{
	echo "# Generated by scripts/installer-copy-payloads.sh — do not commit"
	echo "schema_version: vyntrio-installer-payload-copy-v1"
	echo "slice: \"10.7\""
	echo "target_root: distro/installer/target-sandbox/"
	echo "host_paths_mutated: false"
	echo "contract: docs/ADR/0007-appliance-installer-contract.md"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "preflight_gate: passed"
	echo "payload_source: distro/install-media/envelope/payload/"
	echo "service_enablement: deferred"
	echo "bootstrap_handoff: deferred"
	echo "copied_payloads:"
	for entry in "${PAYLOAD_COPY[@]}"; do
		echo "  - /${entry##*|}"
	done
} >"${resolved_target}/PAYLOAD_COPY.txt"

ok "payload copy record written to target-sandbox/PAYLOAD_COPY.txt"
echo "installer-copy-payloads: complete — manifest payloads copied (no service enablement)"
