#!/usr/bin/env bash
# Stage native Tauri Media Creator packages into distro/release/writer + staging/writer.
# Produces only packages that actually exist on this host. Does not invent macOS .dmg/.app.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
APP_ROOT="${ROOT}/desktop/vyntrio-media-creator"
OUT="${ROOT}/distro/release/writer"
STAGING_WRITER="${ROOT}/distro/release/staging/writer"
VERSION="${VYNTRIO_RELEASE_VERSION:-0.2.0}"

DEB_SRC="${APP_ROOT}/src-tauri/target/release/bundle/deb/Vyntrio Media Creator_${VERSION}_amd64.deb"
APPIMAGE_SRC="${APP_ROOT}/src-tauri/target/release/bundle/appimage/vyntrio-media-creator-${VERSION}-amd64.AppImage"
# Fallback path if tauri named it with spaces:
APPIMAGE_ALT="${APP_ROOT}/src-tauri/target/release/bundle/appimage/Vyntrio Media Creator_${VERSION}_amd64.AppImage"
NSIS_SRC="${APP_ROOT}/src-tauri/target/x86_64-pc-windows-gnu/release/bundle/nsis/Vyntrio Media Creator_${VERSION}_x64-setup.exe"

fail() { echo "package-media-creator-native: $*" >&2; exit 1; }

sha256_file() {
	local path="$1"
	if command -v sha256sum >/dev/null 2>&1; then
		sha256sum "${path}" > "${path}.sha256"
	elif command -v shasum >/dev/null 2>&1; then
		shasum -a 256 "${path}" > "${path}.sha256"
	fi
}

mkdir -p "${OUT}" "${STAGING_WRITER}"

# Withdraw prior loopback-GUI packages claimed as native desktop.
rm -f \
	"${OUT}/vyntrio-media-creator-windows-amd64.exe" \
	"${OUT}/vyntrio-media-creator-windows-amd64.exe.sha256" \
	"${OUT}/vyntrio-media-creator-linux-amd64.tar.gz" \
	"${OUT}/vyntrio-media-creator-linux-amd64.tar.gz.sha256" \
	"${OUT}/vyntrio-media-creator-darwin-arm64" \
	"${OUT}/vyntrio-media-creator-darwin-arm64.sha256" \
	"${OUT}/vyntrio-media-creator-darwin-amd64" \
	"${OUT}/vyntrio-media-creator-darwin-amd64.sha256" \
	"${OUT}/"*.app.zip \
	"${STAGING_WRITER}/vyntrio-media-creator-windows-amd64.exe" \
	"${STAGING_WRITER}/vyntrio-media-creator-windows-amd64.exe.sha256" \
	"${STAGING_WRITER}/vyntrio-media-creator-linux-amd64.tar.gz" \
	"${STAGING_WRITER}/vyntrio-media-creator-linux-amd64.tar.gz.sha256" \
	"${STAGING_WRITER}/vyntrio-media-creator-darwin-arm64" \
	"${STAGING_WRITER}/vyntrio-media-creator-darwin-arm64.sha256" \
	"${STAGING_WRITER}/vyntrio-media-creator-darwin-amd64" \
	"${STAGING_WRITER}/vyntrio-media-creator-darwin-amd64.sha256" \
	2>/dev/null || true

stage_one() {
	local src="$1"
	local dest_name="$2"
	[[ -f "${src}" ]] || fail "missing package: ${src}"
	cp -f "${src}" "${OUT}/${dest_name}"
	chmod a+r "${OUT}/${dest_name}"
	# AppImages must stay executable
	if [[ "${dest_name}" == *.AppImage ]]; then
		chmod a+x "${OUT}/${dest_name}"
	fi
	sha256_file "${OUT}/${dest_name}"
	echo "package-media-creator-native: staged ${OUT}/${dest_name} ($(stat -c '%s' "${OUT}/${dest_name}") bytes)"
}

[[ -f "${DEB_SRC}" ]] || fail "Linux .deb missing — run: cd desktop/vyntrio-media-creator && npm run tauri -- build --bundles deb"
stage_one "${DEB_SRC}" "vyntrio-media-creator-linux-amd64.deb"

if [[ -f "${APPIMAGE_SRC}" ]]; then
	stage_one "${APPIMAGE_SRC}" "vyntrio-media-creator-linux-amd64.AppImage"
elif [[ -f "${APPIMAGE_ALT}" ]]; then
	stage_one "${APPIMAGE_ALT}" "vyntrio-media-creator-linux-amd64.AppImage"
else
	echo "package-media-creator-native: WARN AppImage missing (linuxdeploy/appimagetool blocker earlier); .deb still staged" >&2
fi

[[ -f "${NSIS_SRC}" ]] || fail "Windows NSIS installer missing — run tauri build --target x86_64-pc-windows-gnu --bundles nsis"
stage_one "${NSIS_SRC}" "vyntrio-media-creator-windows-amd64-setup.exe"

cat > "${OUT}/NATIVE_CREATOR.txt" <<EOF
# Generated by scripts/package-media-creator-native.sh — do not commit
schema_version: vyntrio-media-creator-native-v1
framework: tauri
version: ${VERSION}
generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)
packages:
  - vyntrio-media-creator-windows-amd64-setup.exe  # NSIS installer (unsigned; cross-built)
  - vyntrio-media-creator-linux-amd64.deb
  - vyntrio-media-creator-linux-amd64.AppImage
macos:
  status: blocked
  blocker: no macOS build host on this machine; hdiutil unavailable; Tauri .app/.dmg require macOS
withdrawn_as_native_gui:
  - vyntrio-media-creator-windows-amd64.exe   # former Go loopback localhost GUI
  - vyntrio-media-creator-linux-amd64.tar.gz  # former Go loopback tarball
  - vyntrio-media-creator-darwin-*            # Terminal helpers, not native GUI packages
notes:
  - CLI aliases may still be produced by scripts/package-write-media.sh
  - Secure Boot / code signing / notarization not performed
EOF

cp -a "${OUT}/." "${STAGING_WRITER}/"
echo "package-media-creator-native: copied to ${STAGING_WRITER}"
