#!/bin/sh
# Runtime TLS preparation for safe LAN dashboard bind (Stage 2 / Slice 10.4).
#
# POSIX / busybox-sh ONLY. Generates ephemeral self-signed TLS material under
# /run/vyntrio and, when VYNTRIO_LAN_BIND_IP is set, writes a runtime config
# overlay that satisfies the non-loopback bind invariant (cookie_secure + TLS).
#
# Secure-by-default: without VYNTRIO_LAN_BIND_IP the shipped loopback config is
# unchanged; this script only records tls_readiness: ready_loopback_only.
#
# No target-disk writes. No Remote Connect. No certificate manager.
set -u

BASE_CONFIG="${1:-/etc/vyntrio/config.toml}"
TLS_DIR="${VYNTRIO_TLS_DIR:-/run/vyntrio/tls}"
RUNTIME_CONFIG="${VYNTRIO_RUNTIME_CONFIG:-/run/vyntrio/dashboard-config.toml}"
STATUS_FILE="${VYNTRIO_TLS_STATUS:-/run/vyntrio/tls-readiness.txt}"
DASH_PORT="${VYNTRIO_DASHBOARD_PORT:-8080}"
LAN_IP="${VYNTRIO_LAN_BIND_IP:-}"

write_status() {
	mkdir -p "$(dirname "${STATUS_FILE}")" 2>/dev/null || true
	{
		echo "# Generated by prepare-live-dashboard-tls.sh — ephemeral runtime state"
		echo "generated_by: prepare-live-dashboard-tls.sh"
		echo "$@"
	} >"${STATUS_FILE}"
}

mkdir -p /run/vyntrio 2>/dev/null || true

if [ ! -f "${BASE_CONFIG}" ]; then
	write_status "tls_readiness: blocked" "blocker: base_config_missing"
	echo "vyntrio tls-prep: base config missing (${BASE_CONFIG}) — loopback default only" >&2
	exit 0
fi

if ! command -v openssl >/dev/null 2>&1; then
	write_status "tls_readiness: blocked" "blocker: openssl_not_available"
	echo "vyntrio tls-prep: openssl not available — LAN HTTPS bind deferred" >&2
	exit 0
fi

if [ -z "${LAN_IP}" ]; then
	write_status \
		"tls_readiness: ready_loopback_only" \
		"lan_bind: deferred" \
		"lan_bind_enable: set VYNTRIO_LAN_BIND_IP to the appliance LAN address"
	echo "vyntrio tls-prep: TLS path ready; loopback default (set VYNTRIO_LAN_BIND_IP for LAN HTTPS)" >&2
	exit 0
fi

mkdir -p "${TLS_DIR}" 2>/dev/null || {
	write_status "tls_readiness: blocked" "blocker: tls_dir_not_writable"
	echo "vyntrio tls-prep: cannot create ${TLS_DIR}" >&2
	exit 0
}

CERT="${TLS_DIR}/dashboard-cert.pem"
KEY="${TLS_DIR}/dashboard-key.pem"

# Self-signed appliance cert (runtime-only; operator replaces later if desired).
if ! openssl req -x509 -newkey rsa:2048 -nodes \
	-keyout "${KEY}" -out "${CERT}" -days 365 \
	-subj "/CN=vyntrio-appliance" \
	-addext "subjectAltName=IP:${LAN_IP}" \
	2>/dev/null; then
	write_status "tls_readiness: blocked" "blocker: openssl_cert_generation_failed"
	echo "vyntrio tls-prep: certificate generation failed" >&2
	exit 0
fi

chmod 600 "${KEY}" 2>/dev/null || true
chmod 644 "${CERT}" 2>/dev/null || true

mkdir -p "$(dirname "${RUNTIME_CONFIG}")" 2>/dev/null || {
	write_status "tls_readiness: blocked" "blocker: runtime_config_dir_not_writable"
	exit 0
}

cat >"${RUNTIME_CONFIG}" <<EOF
# Runtime LAN dashboard overlay (Slice 10.4) — ephemeral under /run/vyntrio
bind_address = "${LAN_IP}"
listen_port = ${DASH_PORT}
state_dir = "/var/lib/vyntrio"
log_level = "info"
cookie_secure = true
tls_cert_file = "${CERT}"
tls_key_file = "${KEY}"
EOF

write_status \
	"tls_readiness: ready" \
	"lan_bind_ip: ${LAN_IP}" \
	"runtime_config: ${RUNTIME_CONFIG}" \
	"dashboard_url: https://${LAN_IP}:${DASH_PORT}"

echo "vyntrio tls-prep: LAN dashboard HTTPS ready at https://${LAN_IP}:${DASH_PORT}" >&2
exit 0
