#!/usr/bin/env bash
# Stage install-media payloads locally per distro/install-media/build-contract.md.
# Mirrors distro/install-media/manifest.yaml payloads (Slice 9.6).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STAGING_ROOT="${ROOT}/distro/install-media/staging"
PAYLOAD_ROOT="${STAGING_ROOT}/payload"

# source_path|payload_relative_path (mirrors manifest install_path without leading /)
readonly -a PAYLOADS=(
	"bin/vyntrio-api|usr/bin/vyntrio-api"
	"bin/vyntrio-backup|usr/bin/vyntrio-backup"
	"distro/systemd/vyntrio-api.service|etc/systemd/system/vyntrio-api.service"
	"distro/systemd/vyntrio.sysusers|usr/lib/sysusers.d/vyntrio.conf"
	"distro/systemd/vyntrio.tmpfiles.conf|etc/tmpfiles.d/vyntrio.conf"
	"distro/install-media/config.toml.template|etc/vyntrio/config.toml"
)

for entry in "${PAYLOADS[@]}"; do
	src="${ROOT}/${entry%%|*}"
	if [[ ! -e "${src}" ]]; then
		echo "stage-install-media: missing required input: ${entry%%|*}" >&2
		echo "hint: run 'make build' first to produce required binaries" >&2
		exit 1
	fi
done

rm -rf "${STAGING_ROOT}"
mkdir -p "${PAYLOAD_ROOT}"

for entry in "${PAYLOADS[@]}"; do
	src="${ROOT}/${entry%%|*}"
	dest_rel="${entry##*|}"
	dest="${PAYLOAD_ROOT}/${dest_rel}"
	mkdir -p "$(dirname "${dest}")"
	cp -a "${src}" "${dest}"
done

{
	echo "# Generated by scripts/stage-install-media.sh — do not commit"
	echo "schema_version: vyntrio-install-media-manifest-v1"
	echo "media_role: install"
	echo "payload_root: payload/"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "payload_files:"
	for entry in "${PAYLOADS[@]}"; do
		echo "  - ${entry##*|}"
	done
} >"${STAGING_ROOT}/STAGING.txt"

echo "install-media payload staged under ${PAYLOAD_ROOT}"
