#!/usr/bin/env bash
# Swap the image initrd to the hardware-enabled Vyntrio live initramfs
# (Block 9 / Slice 9.17).
#
# Closes the remaining Stage-1 gap: until now the firmware-bootable image booted
# the HOST Debian initrd (staged by Slice 9.12), not the Vyntrio live runtime.
# This slice replaces boot/initrd.img with the live initramfs
# (build/vyntrio-live-initramfs.cpio.gz, produced by Slices 9.15/9.16) and
# rebuilds the firmware image so GRUB boots the Vyntrio live initramfs.
#
# Honesty + safety:
#   - The rebuilt image is STRUCTURALLY verified (via the existing wrapper) and
#     the swap is PROVEN by extracting /boot/initrd.img back out of the image and
#     matching its sha256 to the live initramfs. It is NOT a runtime boot: there
#     is no qemu/VM here, so runtime_boot_tested stays false and
#     dashboard_reachable_on_boot stays false.
#   - Fail-closed, no regression: the host initrd is backed up first; if the
#     swapped image cannot be produced and proven, the host initrd is restored
#     and the known-good BIOS image is rebuilt before exiting non-zero.
#   - No installer/apply behavior, no target-disk writes. The live initramfs is
#     the live runtime; it stays distinct from payload/ (the target-disk artifact).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVELOPE_ROOT="${VYNTRIO_INSTALL_ENVELOPE_ROOT:-${ROOT}/distro/install-media/envelope}"
BUILD_ROOT="${VYNTRIO_INSTALL_MEDIA_BUILD_ROOT:-${ROOT}/distro/install-media/build}"

BOOT="${ENVELOPE_ROOT}/boot"
LIVE_INITRAMFS="${BUILD_ROOT}/vyntrio-live-initramfs.cpio.gz"
HOST_BACKUP="${BUILD_ROOT}/initrd.host-backup.img"
WRAPPER_REC="${BUILD_ROOT}/WRAPPER.txt"
SWAP_REC="${BUILD_ROOT}/INITRD_SWAP.txt"
RAW_NAME="vyntrio-install-media.img"
BIOS_FALLBACK_NAME="vyntrio-install-media-bios.img"

die() { echo "swap-live-initramfs-into-image: $*" >&2; exit 1; }
have() { command -v "$1" >/dev/null 2>&1; }
sha() { sha256sum "$1" 2>/dev/null | cut -d' ' -f1; }
wfield() { sed -n "s/^$1: //p" "${WRAPPER_REC}" 2>/dev/null | head -1; }

# --- preconditions (fail closed on missing inputs) ---
[[ -f "${LIVE_INITRAMFS}" ]] || die "live initramfs missing; run 'make install-media-hardware' first"
[[ -f "${BOOT}/vmlinuz" && -f "${BOOT}/initrd.img" && -f "${BOOT}/grub/grub.cfg" ]] \
	|| die "real boot chain missing; run 'make install-media-image' first"
have sha256sum || die "sha256sum required to prove the swap"
have gzip || die "gzip required"
have cpio || die "cpio required"

# --- verify the live initramfs really is the Vyntrio live runtime ---
listing="$(gzip -dc "${LIVE_INITRAMFS}" 2>/dev/null | cpio -t 2>/dev/null || true)"
grep -qE '^\.?/?init$' <<<"${listing}" || die "live initramfs has no /init at root; refusing to swap"
grep -q 'bin/busybox' <<<"${listing}" || die "live initramfs has no busybox; refusing to swap"
LIVE_HAS_MODULES=false
grep -qE 'lib/modules/[^/]+/modules\.dep' <<<"${listing}" && LIVE_HAS_MODULES=true

LIVE_SHA="$(sha "${LIVE_INITRAMFS}")"
LIVE_BYTES="$(stat -c '%s' "${LIVE_INITRAMFS}")"
CUR_SHA="$(sha "${BOOT}/initrd.img")"

# --- host initrd provenance / backup (idempotent) ---
ALREADY_SWAPPED=false
if [[ "${CUR_SHA}" == "${LIVE_SHA}" ]]; then
	ALREADY_SWAPPED=true
else
	# Current boot/initrd.img is the host initrd; refresh the backup.
	cp -f "${BOOT}/initrd.img" "${HOST_BACKUP}"
fi
HOST_SHA="unknown"
HOST_BYTES="0"
if [[ -f "${HOST_BACKUP}" ]]; then
	HOST_SHA="$(sha "${HOST_BACKUP}")"
	HOST_BYTES="$(stat -c '%s' "${HOST_BACKUP}")"
fi

rewrap() { bash "${ROOT}/scripts/wrap-install-media-image.sh" "$@"; }

restore_and_fail() {
	local reason="$1"
	if [[ -f "${HOST_BACKUP}" ]]; then
		cp -f "${HOST_BACKUP}" "${BOOT}/initrd.img"
		rewrap >/dev/null 2>&1 || true   # rebuild the known-good host-initrd image
	fi
	{
		echo "# Generated by scripts/swap-live-initramfs-into-image.sh — do not commit"
		echo "schema_version: vyntrio-install-media-initrd-swap-v1"
		echo "slice: 9.17"
		echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
		echo "media_role: install"
		echo "swap_status: failed"
		echo "blocker: ${reason}"
		echo "host_initrd_restored: $([[ -f "${HOST_BACKUP}" ]] && echo true || echo false)"
		echo "firmware_bootable: $(wfield firmware_bootable)"
		echo "note: fail-closed — image left booting the host initrd to avoid regression"
	} >"${SWAP_REC}"
	echo "install-media initrd-swap: FAILED — ${reason}; host initrd restored" >&2
	exit 1
}

# --- THE SWAP: image initrd := Vyntrio live initramfs ---
cp -f "${LIVE_INITRAMFS}" "${BOOT}/initrd.img"

# --- rebuild the firmware image from the swapped boot tree (existing wrapper) ---
rewrap >/dev/null 2>&1 || restore_and_fail "wrapper failed to rebuild image after swap"

FW="$(wfield firmware_bootable)"
FMT="$(wfield artifact_format)"
ART="$(wfield artifact)"
STRUCT="$(sed -n 's/^structural_verification: //p' "${WRAPPER_REC}" 2>/dev/null | head -1)"

[[ "${FW}" == "true" ]] || restore_and_fail "rebuilt image is not firmware-bootable (see WRAPPER.txt blockers)"
[[ "${STRUCT}" == "pass" ]] || restore_and_fail "rebuilt image failed structural verification"

# --- PROVE the swap: extract /boot/initrd.img from the image, match sha256 ---
IMG_INITRD_MATCHES=false
EXTRACT_METHOD="none"
IMG_INITRD_SHA="unavailable"
case "${FMT}" in
raw_gpt_hybrid_disk)
	img="${ROOT}/${ART}"
	[[ -f "${img}" ]] || restore_and_fail "wrapper reported hybrid image but artifact missing: ${ART}"
	esp_off="$(cat "${BUILD_ROOT}/HYBRID_ESP_OFFSET.txt" 2>/dev/null || true)"
	[[ -n "${esp_off}" ]] || restore_and_fail "HYBRID_ESP_OFFSET.txt missing after hybrid wrap"
	if have mcopy; then
		work="$(mktemp -d)"
		extracted="${work}/initrd.extracted"
		export MTOOLS_SKIP_CHECK=1
		if mcopy -i "${img}@@${esp_off}" ::boot/initrd.img "${extracted}" >/dev/null 2>&1 && [[ -s "${extracted}" ]]; then
			IMG_INITRD_SHA="$(sha "${extracted}")"
			[[ "${IMG_INITRD_SHA}" == "${LIVE_SHA}" ]] && IMG_INITRD_MATCHES=true
			EXTRACT_METHOD="mtools_dump_from_esp"
		fi
		rm -rf "${work}"
	fi
	if [[ "${IMG_INITRD_MATCHES}" != true ]]; then
		restore_and_fail "image /boot/initrd.img sha (${IMG_INITRD_SHA}) does not match live initramfs (${LIVE_SHA})"
	fi
	;;
raw_mbr_bios_disk)
	img="${ROOT}/${ART}"
	[[ -f "${img}" ]] || restore_and_fail "wrapper reported raw image but artifact missing: ${ART}"
	if have debugfs; then
		work="$(mktemp -d)"
		part="${work}/part.img"
		extracted="${work}/initrd.extracted"
		# Partition starts at 1MiB (sector 2048); carve it out and read via debugfs.
		dd if="${img}" bs=1M skip=1 of="${part}" status=none 2>/dev/null || true
		if debugfs -R "dump /boot/initrd.img ${extracted}" "${part}" >/dev/null 2>&1 && [[ -s "${extracted}" ]]; then
			IMG_INITRD_SHA="$(sha "${extracted}")"
			[[ "${IMG_INITRD_SHA}" == "${LIVE_SHA}" ]] && IMG_INITRD_MATCHES=true
			EXTRACT_METHOD="debugfs_dump_from_partition"
		fi
		rm -rf "${work}"
	fi
	if [[ "${IMG_INITRD_MATCHES}" != true ]]; then
		restore_and_fail "image /boot/initrd.img sha (${IMG_INITRD_SHA}) does not match live initramfs (${LIVE_SHA})"
	fi
	;;
iso9660_eltorito)
	# grub-mkrescue copies boot/ verbatim; boot/initrd.img now == live initramfs.
	if [[ "$(sha "${BOOT}/initrd.img")" == "${LIVE_SHA}" ]]; then
		IMG_INITRD_MATCHES=true
		EXTRACT_METHOD="boot_tree_verbatim_copy"
		IMG_INITRD_SHA="${LIVE_SHA}"
	else
		restore_and_fail "boot/initrd.img sha does not match live initramfs after swap"
	fi
	;;
*)
	restore_and_fail "unexpected artifact_format after swap: ${FMT}"
	;;
esac

# --- success record (honest: proven swap, unverified runtime) ---
{
	echo "# Generated by scripts/swap-live-initramfs-into-image.sh — do not commit"
	echo "schema_version: vyntrio-install-media-initrd-swap-v1"
	echo "slice: 9.17"
	echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
	echo "media_role: install"
	echo "swap_status: applied"
	echo "already_swapped_on_entry: ${ALREADY_SWAPPED}"
	echo "initrd_before:"
	echo "  source: host_debian_initrd"
	echo "  bytes: ${HOST_BYTES}"
	echo "  sha256: ${HOST_SHA}"
	echo "  backup: distro/install-media/build/$(basename "${HOST_BACKUP}")"
	echo "initrd_after:"
	echo "  source: vyntrio_live_initramfs"
	echo "  bytes: ${LIVE_BYTES}"
	echo "  sha256: ${LIVE_SHA}"
	echo "  has_kernel_modules: ${LIVE_HAS_MODULES}"
	echo "  origin: distro/install-media/build/$(basename "${LIVE_INITRAMFS}")"
	echo "image:"
	echo "  artifact: ${ART}"
	echo "  artifact_format: ${FMT}"
	echo "  firmware_bootable: ${FW}"
	echo "  structural_verification: ${STRUCT}"
	echo "  boots_live_initramfs: ${IMG_INITRD_MATCHES}"
	echo "  image_initrd_sha256: ${IMG_INITRD_SHA}"
	echo "  swap_proof: ${EXTRACT_METHOD}"
	echo "honest_limits:"
	echo "  runtime_boot_tested: false"
	echo "  runtime_boot_reason: no_qemu_or_vm_on_build_host"
	echo "  dashboard_reachable_on_boot: false"
	echo "  boot_cmdline_note: >-"
	echo "    grub.cfg retains the 'boot=live' Debian hint, but the Vyntrio live"
	echo "    initramfs ships its own /init (PID 1) which ignores it; /init performs"
	echo "    the hardware bring-up (Slice 9.16) and first-boot path (Slice 9.14)."
	echo "missing_to_close_stage1:"
	echo "  - runtime_boot_verification_on_vm_or_hardware"
	echo "  - dashboard_reachable_on_boot_proof"
	echo "missing_for_usb_creator:"
	echo "  - host_usb_writer_tool"
} >"${SWAP_REC}"

echo "install-media initrd-swap: swapped host initrd -> Vyntrio live initramfs (${LIVE_BYTES} bytes)"
echo "install-media initrd-swap: image=${ART} firmware_bootable=${FW} structural=${STRUCT} boots_live_initramfs=${IMG_INITRD_MATCHES} (${EXTRACT_METHOD})"
echo "install-media initrd-swap: runtime_boot_tested=false dashboard_reachable_on_boot=false — see build/INITRD_SWAP.txt" >&2
