#!/usr/bin/env bash
# Runtime boot verification on a real boot-capable harness (Stage 2 / Slice 10.1).
#
# Turns the structurally-bootable, initrd-swapped image (Stage 1 / Slice 9.17)
# into a *booted* runtime proof — or an explicit, honest fail-closed skip with
# exact blockers when no boot harness exists.
#
# HARD RULES (enforced by design):
#   - This script is READ-ONLY with respect to the boot/image chain and the live
#     rootfs. It never writes envelope/boot, envelope/live_root, or the image
#     artifacts. If no harness exists it does NOT compensate by changing anything;
#     it records blockers and exits non-zero (fail closed).
#   - Dashboard reachability proof = an ACTUAL HTTP response from the booted guest
#     (via qemu user-net hostfwd). A chroot probe or structural inference is NOT a
#     dashboard-on-boot proof and is never claimed as one here.
#   - No installer/apply behavior, no target-disk writes.
#
# NOTE: "Slice 10.1" here is the first Stage-2 (first-boot dashboard) slice. It is
# unrelated to the staged-installer "Block 10" (secondary internal infrastructure).
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENVELOPE_ROOT="${VYNTRIO_INSTALL_ENVELOPE_ROOT:-${ROOT}/distro/install-media/envelope}"
BUILD_ROOT="${VYNTRIO_INSTALL_MEDIA_BUILD_ROOT:-${ROOT}/distro/install-media/build}"

SWAP_REC="${BUILD_ROOT}/INITRD_SWAP.txt"
WRAP_REC="${BUILD_ROOT}/WRAPPER.txt"
VERIFY_REC="${BUILD_ROOT}/RUNTIME_VERIFY.txt"
SERIAL_LOG="${BUILD_ROOT}/runtime-verify-serial.log"

GUEST_DASH_PORT=8080                                        # firstboot.sh serves here
HTTP_PORT="${VYNTRIO_RUNTIME_HTTP_PORT:-8088}"             # host-forwarded port
BOOT_TIMEOUT="${VYNTRIO_RUNTIME_BOOT_TIMEOUT:-120}"

die() { echo "verify-live-boot-runtime: $*" >&2; exit 2; }
have() { command -v "$1" >/dev/null 2>&1; }
rec_get() { sed -n "s/^ *$1: //p" "$2" 2>/dev/null | head -1; }

mkdir -p "${BUILD_ROOT}"

# --- read-only Stage-1 intactness check -------------------------------------
[[ -f "${SWAP_REC}" ]] || die "INITRD_SWAP.txt missing; Stage 1 not complete (run 'make install-media-initrd-swap')"
[[ -f "${WRAP_REC}" ]] || die "WRAPPER.txt missing; Stage 1 not complete"

BOOTS_LIVE="$(rec_get boots_live_initramfs "${SWAP_REC}")"
SWAP_STATUS="$(rec_get swap_status "${SWAP_REC}")"
FW_BOOTABLE="$(sed -n 's/^firmware_bootable: //p' "${WRAP_REC}" | head -1)"
ARTIFACT="$(sed -n 's/^artifact: //p' "${WRAP_REC}" | head -1)"
ARTIFACT_FMT="$(sed -n 's/^artifact_format: //p' "${WRAP_REC}" | head -1)"
IMG_ABS="${ROOT}/${ARTIFACT}"

STAGE1_OK=true
STAGE1_REASON=""
if [[ "${SWAP_STATUS}" != "applied" || "${BOOTS_LIVE}" != "true" ]]; then
	STAGE1_OK=false; STAGE1_REASON="initrd swap not applied / image does not boot live initramfs"
elif [[ "${FW_BOOTABLE}" != "true" || "${ARTIFACT_FMT}" != "raw_mbr_bios_disk" ]]; then
	STAGE1_OK=false; STAGE1_REASON="no firmware-bootable raw image recorded"
elif [[ ! -f "${IMG_ABS}" ]]; then
	STAGE1_OK=false; STAGE1_REASON="image artifact missing: ${ARTIFACT}"
fi

# --- harness detection (read-only) ------------------------------------------
QEMU=""
for q in qemu-system-x86_64 qemu-system-i386; do have "${q}" && { QEMU="${q}"; break; }; done
ACCEL="tcg"; [[ -e /dev/kvm ]] && ACCEL="kvm"
HARNESS="none"; [[ -n "${QEMU}" ]] && HARNESS="qemu"

RUNTIME_TESTED=false
BOOT_MARKERS=""
DASH_STATUS=""
DASH_REACHABLE=false
DASH_METHOD="none"
STATUS="blocked"
declare -a BLOCKERS=()

write_record() {
	{
		echo "# Generated by scripts/verify-live-boot-runtime.sh — do not commit"
		echo "schema_version: vyntrio-install-media-runtime-verify-v1"
		echo "slice: \"10.1\""
		echo "stage: \"2\""
		echo "subsystem: install-media-runtime-verification"
		echo "generated_at: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
		echo "media_role: install"
		echo "not_block10_installer: staged installer is secondary internal infrastructure; this is Stage-2 boot verification"
		echo "stage1_boot_to_runtime_intact: ${STAGE1_OK}"
		[[ -n "${STAGE1_REASON}" ]] && echo "stage1_regression_reason: ${STAGE1_REASON}"
		echo "image: ${ARTIFACT}"
		echo "image_boots_live_initramfs: ${BOOTS_LIVE:-unknown}"
		echo "chain_modified_by_this_slice: false"
		echo "harness: ${HARNESS}"
		echo "harness_accel: $([[ "${HARNESS}" == qemu ]] && echo "${ACCEL}" || echo none)"
		echo "runtime_boot_tested: ${RUNTIME_TESTED}"
		if [[ "${RUNTIME_TESTED}" == true ]]; then
			echo "vm_harness: ${QEMU}"
			echo "boot_markers: ${BOOT_MARKERS:-none}"
			echo "serial_log: distro/install-media/build/$(basename "${SERIAL_LOG}")"
		fi
		echo "dashboard_probe_method: ${DASH_METHOD}"
		[[ -n "${DASH_STATUS}" ]] && echo "dashboard_http_status: ${DASH_STATUS}"
		echo "dashboard_reachable_on_boot: ${DASH_REACHABLE}"
		echo "status: ${STATUS}"
		echo "blockers:"
		if [[ "${#BLOCKERS[@]}" -eq 0 ]]; then
			echo "  - none"
		else
			for b in "${BLOCKERS[@]}"; do echo "  - ${b}"; done
		fi
		echo "missing_for_dashboard_on_boot_proof:"
		if [[ "${DASH_REACHABLE}" == true ]]; then
			echo "  - none"
		else
			[[ "${HARNESS}" == none ]] && echo "  - vm_or_hardware_boot_harness"
			echo "  - booted_guest_http_200_from_vyntrio_api"
		fi
		echo "honest_note: >-"
		echo "  dashboard_reachable_on_boot is only ever set true by an actual HTTP 200"
		echo "  from the booted guest (qemu user-net hostfwd). chroot/structural checks"
		echo "  from earlier slices do NOT count as a dashboard-on-boot proof."
	} >"${VERIFY_REC}"
}

# --- Stage-1 regression is a blocking finding (still no chain modification) ---
if [[ "${STAGE1_OK}" != true ]]; then
	STATUS="stage1_regression"
	BLOCKERS+=("stage1_regression: ${STAGE1_REASON}")
	BLOCKERS+=("action: re-run Stage 1 ('make install-media-initrd-swap'); this slice does not modify the chain")
	write_record
	echo "verify-live-boot-runtime: STAGE 1 REGRESSION — ${STAGE1_REASON}" >&2
	exit 1
fi

# --- no harness: fail closed, exact blockers, NO chain modification ----------
if [[ "${HARNESS}" == "none" ]]; then
	STATUS="blocked"
	BLOCKERS+=("no_vm_harness: qemu-system-x86_64/qemu-system-i386 not installed (apt: qemu-system-x86)")
	[[ ! -e /dev/kvm ]] && BLOCKERS+=("no_kvm: /dev/kvm absent (nested virt/accel unavailable; TCG would still work if qemu were present)")
	BLOCKERS+=("no_hardware_harness: no automated bare-metal boot+serial capture configured")
	BLOCKERS+=("policy: per Stage-2 rules, the image/initrd/bootloader/live-rootfs were NOT modified to compensate")
	write_record
	echo "verify-live-boot-runtime: NO BOOT HARNESS — runtime boot not exercised; blockers recorded (fail-closed)" >&2
	echo "verify-live-boot-runtime: image/initrd/bootloader/live-rootfs left unchanged (read-only verification)" >&2
	exit 1
fi

# --- harness present: boot the image and probe the dashboard over HTTP -------
rm -f "${SERIAL_LOG}"
declare -a QEMU_ARGS=(
	-drive "file=${IMG_ABS},format=raw,if=ide"
	-m 1024 -no-reboot -nographic -display none
	-serial "file:${SERIAL_LOG}"
	-netdev "user,id=net0,hostfwd=tcp:127.0.0.1:${HTTP_PORT}-:${GUEST_DASH_PORT}"
	-device "e1000,netdev=net0"
)
[[ "${ACCEL}" == "kvm" ]] && QEMU_ARGS+=(-enable-kvm)

set +e
timeout "${BOOT_TIMEOUT}" "${QEMU}" "${QEMU_ARGS[@]}" >/dev/null 2>&1 &
QPID=$!
# Poll the forwarded dashboard port for a real HTTP response while the guest boots.
if have curl; then
	DASH_METHOD="booted_guest_http_hostfwd"
	for _ in $(seq 1 "${BOOT_TIMEOUT}"); do
		kill -0 "${QPID}" 2>/dev/null || break
		DASH_STATUS="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${HTTP_PORT}/" 2>/dev/null || true)"
		[[ "${DASH_STATUS}" == "200" ]] && { DASH_REACHABLE=true; break; }
		sleep 1
	done
else
	BLOCKERS+=("no_curl: cannot perform the booted-guest HTTP dashboard probe (apt: curl)")
fi
kill "${QPID}" >/dev/null 2>&1 || true
wait "${QPID}" 2>/dev/null
set -e
RUNTIME_TESTED=true

if [[ -f "${SERIAL_LOG}" ]]; then
	grep -qa 'GRUB' "${SERIAL_LOG}" && BOOT_MARKERS+="grub "
	grep -qaE 'Linux version|Decompressing Linux|Booting' "${SERIAL_LOG}" && BOOT_MARKERS+="kernel "
	grep -qa 'vyntrio live-init' "${SERIAL_LOG}" && BOOT_MARKERS+="live-init "
	grep -qa 'vyntrio hw-init' "${SERIAL_LOG}" && BOOT_MARKERS+="hw-init "
	grep -qa 'vyntrio firstboot' "${SERIAL_LOG}" && BOOT_MARKERS+="firstboot "
fi

if [[ "${DASH_REACHABLE}" == true ]]; then
	STATUS="dashboard_reachable"
elif [[ -n "${BOOT_MARKERS}" ]]; then
	STATUS="boot_without_dashboard"
	BLOCKERS+=("dashboard_unreachable: booted (markers: ${BOOT_MARKERS}) but no HTTP 200 on :${GUEST_DASH_PORT} within ${BOOT_TIMEOUT}s")
else
	STATUS="no_boot_markers"
	BLOCKERS+=("no_boot_markers: serial log lacked GRUB/kernel/live-init markers within ${BOOT_TIMEOUT}s")
fi

write_record

echo "verify-live-boot-runtime: harness=${HARNESS}/${ACCEL} runtime_boot_tested=${RUNTIME_TESTED} status=${STATUS}"
echo "verify-live-boot-runtime: boot_markers='${BOOT_MARKERS:-none}' dashboard_http=${DASH_STATUS:-none} dashboard_reachable_on_boot=${DASH_REACHABLE}"

# Success only when the dashboard actually answered from the booted guest.
[[ "${DASH_REACHABLE}" == true ]] || { echo "verify-live-boot-runtime: dashboard-on-boot NOT proven — fail closed; see build/RUNTIME_VERIFY.txt" >&2; exit 1; }
